### ISSUE TITLE
Regex Pattern got misinterpreted?

### ISSUE THREAD

**Issue by stiivo** [mysqludf/lib_mysqludf_preg#21]
MySQL-Version: 5.5.46-0+deb7u1-log on Debian 7.9

MySQL-Testing-Table:

```
CREATE TABLE IF NOT EXISTS `preg_test` (    
  `test` varchar(255) NOT NULL    
) ENGINE=InnoDB DEFAULT CHARSET=latin1;    

INSERT INTO `preg_test` (`test`) VALUES    
('(1x12345+2x12345)'),    
('(12345)'),    
('(12345+12345)'),    
('foobar [foo 12345]');
```

Example command:

```
SELECT * FROM preg_test WHERE PREG_RLIKE('/(\([0-9]x[0-9]{5}\+[0-9]x[0-9]{5}\)|\([0-9]{5}\)|\([0-9]{5}\+[0-9]{5}\))/', test)
```

Output:

```
+--------------------+
| test               |
+--------------------+
| (1x12345+2x12345)  |
| (12345)            |
| (12345+12345)      |
| foobar [foo 12345] |
+--------------------+
4 rows in set (0.01 sec)
```

Imo subject 4 should not be shown. I checked my pattern [here](https://regex101.com/r/eA0xM3/1) and it should be all right. I hope i was precise as possible.

Thanks for your work.

Regards,
Steven

**Comment by vlad-ya** [comment]
stvn1911, you are incorrectly escaping your "(" ")".
Your "\(" is just "(" because single "\" is the escape character in MySQL and it does his job on the "query preparation" level and it "disappears" before strings are passed to the UDF. So it doesn't do any escape for the regexp itself but just for the SQL query. To escape your "()" you should supply "\\(" and "\\)" (with double backslashes) that will deliver a backslash ("\") character to the regexp.

See
http://dev.mysql.com/doc/refman/5.7/en/string-literals.html#character-escape-sequences
http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_backslash_escapes

Hope this helps.

**Comment by vlad-ya** [comment]
So I say that there is no issue.

**Comment by stiivo** [comment]
Thank you very much. I was quite sure the mistake was on my side! :+1:
